mysite/microblog/urls.py
from django.urls import path
from . import views

app_name = 'microblog'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('user/<str:username>', views.user, name='user'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('follow/<str:username>', views.follow, name='follow'),
    path('unfollow/<str:username>', views.unfollow, name='unfollow'),
    path('explore/', views.explore, name='explore')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('microblog/', include('microblog.urls')),
    path('admin/', admin.site.urls),
]

mysite/microblog/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.models import AbstractUser
from hashlib import md5


# Create your models here.
class User(AbstractUser):
    username = models.CharField(max_length=64, db_index=True, unique=True)
    email = models.EmailField(unique=True, db_index=True)
    password = models.CharField(max_length=128)
    about_me = models.CharField(max_length=140, null=True)
    following = models.ManyToManyField(to='User')  # users followed by this user

    def __str__(self):
        return '<User {}>'.format(self.username)

    def avatar_128(self):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, 128)

    def avatar_36(self):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            digest, 36)

    def is_following(self, user):
        return self.following.filter(username=user.username).count() > 0

    def follow(self, user):
        if not self.is_following(user):
            self.following.add(user)

    def unfollow(self, user):
        if self.is_following(user):
            self.following.remove(user)

    def followed_posts(self):
        selfuser = User.objects.prefetch_related('following__post').get(username=self.username)
        all_posts = Post.objects.filter(user__username=selfuser.username).all()
        for u in selfuser.following.all():
            all_posts = all_posts | u.post.all()
        return all_posts.order_by('timestamp')


class Post(models.Model):
    body = models.CharField(max_length=140)
    timestamp = models.DateTimeField(db_index=True, default=datetime.utcnow)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')

    def __repr__(self):
        return '<Post {}>'.format(self.body)

mysite/microblog/forms.py
from django import forms
from django.forms import fields, EmailField
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginForm(forms.Form):
    username = fields.CharField(required=True)
    password = fields.CharField(widget=forms.PasswordInput, required=True)
    remember_me = fields.BooleanField(required=False)


class EditProfileForm(forms.Form):
    username = fields.CharField(label='Username')
    about_me = fields.CharField(label='About me', min_length=0, max_length=140, required=False,
                                widget=forms.Textarea(attrs={'cols': 50, 'rows': 20}))


class RegistrationForm(forms.Form):
    username = fields.CharField(required=True, error_messages={'required': 'username cannot be empty'})
    email = fields.EmailField(required=True, error_messages={'required': 'email cannot be empty'})
    password = fields.CharField(widget=forms.PasswordInput, required=True,
                                error_messages={'required': 'password cannot be empty'})
    password2 = fields.CharField(widget=forms.PasswordInput, required=True,
                                 error_messages={'required': 'password cannot be empty'})

    def clean_username(self):
        user = User.objects.filter(username=self.cleaned_data['username']).first()
        if user is not None:
            raise ValidationError(message='Please use a different username.', code='invalid')
        else:
            return self.cleaned_data['username']

    def clean_email(self):
        user = User.objects.filter(email=self.cleaned_data['email']).first()
        if user is not None:
            raise ValidationError(message='Please use a different email address.', code='invalid')
        else:
            return self.cleaned_data['email']

    def clean_password2(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password2'):
            raise ValidationError(message='field must be equal to password', code='invalid')
        else:
            return self.cleaned_data


class EmptyForm(forms.Form):
    pass


class PostForm(forms.Form):
    post = fields.CharField(required=True, max_length=140, min_length=1,
                            widget=forms.Textarea(attrs={'cols': 50, 'rows': 10}))

'''
class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')
        widgets = {
            'password': forms.PasswordInput()
        }

    def clean_username(self):
        user = User.objects.filter(username=self.cleaned_data['username']).first()
        if user is None:
            raise ValidationError(message='username is invalid.', code='invalid')
        else:
            return self.cleaned_data['username']

'''
'''
class RegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email')
        widgets = {
            'email': forms.EmailInput(),
        }

        def clean_username(self):
            user = User.objects.filter(username=self.cleaned_data['username']).first()
            if user is not None:
                raise ValidationError(message='Please use a different username.', code='invalid')
            else:
                return self.cleaned_data['username']

        def clean_email(self):
            user = User.objects.filter(email=self.cleaned_data['email']).first()
            if user is not None:
                raise ValidationError(message='Please use a different email address.', code='invalid')
            else:
                return self.cleaned_data['email']
'''

mysite/microblog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import LoginForm, RegistrationForm, EditProfileForm, EmptyForm, PostForm
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import get_user, login as Login, logout as Logout
from django.contrib.auth.decorators import login_required
from .models import User, Post
from django.core.paginator import Paginator
import json


@login_required(login_url='/microblog/login/')
# Create your views here.
def index(request):
    current_user = get_user(request)

    form = PostForm(request.POST)
    if form.is_valid():
        formdata = form.cleaned_data
        post = Post(body=formdata['post'], user=current_user)
        post.save()
        messages.add_message(request, messages.INFO, 'Your post is now live')
        return HttpResponseRedirect(reverse('microblog:index'))

    '''
    posts = [
        {
            'author': {'username': 'John'},
            'body': 'Beautiful day in Portland!'
        },
        {
            'author': {'username': 'Susan'},
            'body': 'The Avengers movie was so cool!'
        }
    ]
    '''
    posts = current_user.followed_posts().all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'microblog/index.html', {'title': 'Home', 'current_user': current_user, 'posts': posts,
                                                    'form': form, 'page_obj': page_obj})


@login_required(login_url='/microblog/login/')
def user(request, username):
    current_user = get_user(request)
    user = User.objects.filter(username=username).first()
    following = current_user.is_following(user)

    posts = user.post.order_by('-timestamp')
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'microblog/user.html', {'user': user, 'posts': posts, 'current_user': current_user,
                                                   'following': following, 'page_obj': page_obj})


@login_required(login_url='/microblog/login')
def explore(request):
    current_user = get_user(request)
    posts = Post.objects.order_by('-timestamp').all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'microblog/index.html', {'title': 'Explore', 'posts': posts, 'current_user': current_user,
                                                    'page_obj': page_obj})


def login(request):
    if get_user(request).is_authenticated:
        return HttpResponseRedirect(reverse('microblog:index'))
    form = LoginForm(request.POST)
    if form.is_valid():
        formdata = form.cleaned_data
        user = User.objects.filter(username=formdata['username']).first()
        if user is None or not user.check_password(formdata['password']):
            messages.add_message(request, messages.INFO, 'Invalid username or password')
            return HttpResponseRedirect(reverse('microblog:login'))
        Login(request, user)
        next_page = request.GET.get('next')
        if not next_page:
            next_page = reverse('microblog:index')
        messages.add_message(request, messages.INFO, 'Login requested for user {}, remember_me={}'.format(
            formdata['username'], formdata['remember_me']))
        return HttpResponseRedirect(next_page)
    return render(request, 'microblog/login.html', {'form': form})


def logout(request):
    Logout(request)
    return HttpResponseRedirect(reverse('microblog:index'))


def register(request):
    if get_user(request).is_authenticated:
        return HttpResponseRedirect(reverse('microblog:index'))
    form = RegistrationForm(request.POST)
    if form.is_valid():
        formdata = form.cleaned_data
        user = User(username=formdata['username'], email=formdata['email'])
        user.set_password(formdata['password'])
        user.save()
        messages.add_message(request, messages.INFO, 'Congratulations, you are now a registered user!')
        return HttpResponseRedirect(reverse('microblog:login'))
    return render(request, 'microblog/register.html', {'title': 'Register', 'form': form})


@login_required(login_url='/microblog/login/')
def edit_profile(request):
    form = EditProfileForm(request.POST)

    current_user = get_user(request)
    if form.is_valid():
        formdata = form.cleaned_data
        current_user.username = formdata['username']
        current_user.about_me = formdata['about_me']
        current_user.save()
        return HttpResponseRedirect(reverse('microblog:user', args=(current_user.username,)))
    return render(request, 'microblog/edit_profile.html', {'form': form, 'current_user': current_user})


@login_required(login_url='/microblog/login/')
def follow(request, username):
    current_user = get_user(request)
    form = EmptyForm(request)
    if form.is_valid():
        user = User.objects.filter(username=username).first()
        if user is None:
            messages.add_message(request, messages.INFO, 'User {} not found.'.format(username))
            return HttpResponseRedirect(reverse('microblog:index'))
        if user == current_user:
            messages.add_message(request, messages.INFO, 'You cannot follow yourself'.format(username))
            return HttpResponseRedirect(reverse('microblog:user', args=(user.username,)))
        current_user.follow(user)
        messages.add_message(request, messages.INFO, 'You are following {}'.format(username))
        return HttpResponseRedirect(reverse('microblog:user', args=(user.username,)))
    else:
        print('invalid')
        return HttpResponseRedirect(reverse('microblog:index'))


@login_required(login_url='/microblog/login/')
def unfollow(request, username):
    current_user = get_user(request)
    form = EmptyForm(request)
    if form.is_valid():
        user = User.objects.filter(username=username).first()
        if user is None:
            messages.add_message(request, messages.INFO, 'User {} not found.'.format(username))
            return HttpResponseRedirect(reverse('microblog:index'))
        if user == current_user:
            messages.add_message(request, messages.INFO, 'You cannot unfollow yourself'.format(username))
            return HttpResponseRedirect(reverse('microblog:user', args=(user.username,)))
        current_user.unfollow(user)
        messages.add_message(request, messages.INFO, 'You are not following {}'.format(username))
        return HttpResponseRedirect(reverse('microblog:user', args=(user.username,)))
    else:
        print('invalid')
        return HttpResponseRedirect(reverse('microblog:index'))

mysite/microblog/templates/microblog/base.html
{% extends 'microblog/bootstrap.html' %}
{% load bootstrap3 %}

{% block title %}
    {% if title %}{{ title }} - Microblog{% else %}Welcome to Microblog{% endif %}
{% endblock %}



{% block bootstrap3_content %}
    {% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'microblog:index' %}">Microblog</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'microblog:index' %}">Home</a></li>
                    <li><a href="{% url 'microblog:explore' %}">Explore</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if not current_user.is_authenticated %}
                    <li><a href="{% url 'microblog:login' %}">Login</a></li>
                    {% else %}
                    <li><a href="{% url 'microblog:user' current_user.username %}">Profile</a></li>
                    <li><a href="{% url 'microblog:logout' %}">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% endblock %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

mysite/microblog/templates/microblog/base_bak.html
{% load bootstrap3 %}
<html>
    <head>
        {% if title %}
        <title>{{ title }} - Microblog</title>
        {% else %}
        <title>Welcome to Microblog</title>
        {% endif %}
    </head>
    <body>
        <div>
            Microblog:
            <a href="{% url 'microblog:index' %}">Home</a>
            {% if current_user.is_authenticated %}
            <a href="{% url 'microblog:logout' %}">Logout</a>
            <a href="{% url 'microblog:user' current_user.username %}">Profile</a>
            <a href="{% url 'microblog:explore' %}">Explore</a>
            {% else %}
            <a href="{% url 'microblog:login' %}">Login</a>
            {% endif %}
        </div>
        <hr>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% block content %}{% endblock %}
    </body>
</html>

mysite/microblog/templates/microblog/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

mysite/microblog/templates/microblog/edit_profile.html
{% extends "microblog/base.html" %}
{% load bootstrap3 %}

{% block app_content %}
    <h1>Edit Profile</h1>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='submit' %}{% endbuttons %}
    </form>
{% endblock %}

mysite/microblog/templates/microblog/edit_profile_bak.html
{% extends "microblog/base.html" %}

{% block content %}
    <h1>Edit Profile</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>
            {{ form.username.label }}<br>
            {{ form.username }}<br>
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </p>
        <p>
            {{ form.about_me.label }}<br>
            {{ form.about_me }}<br>
            <span style="color: red;">{{ form.about_me.errors.0 }}</span>
        </p>
        <p><input type="submit" value="Submit"></p>
    </form>
{% endblock %}

mysite/microblog/templates/microblog/index.html
{% extends "microblog/base.html" %}

{% load bootstrap3 %}

{% block app_content %}
    <h1>Hi, {{ current_user.username }}!</h1>
    {% if form %}
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='submit' %}{% endbuttons %}
    </form>
    {% endif %}
    {% for post in page_obj %}
    <p>
    <a href="{% url 'microblog:user' post.user.username %}">{{ post.user.username }}</a> says: <b>{{ post.body }}</b>
    </p>
    {% endfor %}
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li>
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

mysite/microblog/templates/microblog/login.html
{% extends "microblog/base.html" %}
{% load bootstrap3 %}

{% block app_content %}
    <h1>Sign In</h1>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='submit' %}{% endbuttons %}
    </form>
    <p>New User? <a href="{% url 'microblog:register' %}">Click to Register!</a></p>
    <p>
        Forgot Your Password?
        <a href="{% url 'microblog:register' %}">Click to Reset It</a>
    </p>
{% endblock %}

mysite/microblog/templates/microblog/login_bak.html
{% extends "microblog/base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>
            {{ form.username.label }}<br>
            {{ form.username }}<br>
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password }}<br>
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </p>
        <p>{{ form.remember_me }} {{ form.remember_me.label }}</p>
        <p><input type="submit" value="Login"></p>
        <p>New User? <a href="{% url 'microblog:register' %}">Click to Register!</a></p>
    </form>
{% endblock %}

mysite/microblog/templates/microblog/login_new.html
{% extends "microblog/base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label }}<br>
            {{ field }}<br>
            <span style="color: red;">{{ field.errors }}</span>
        </p>
        {% endfor %}
        <p><input type="submit" value="Login"></p>
        <p>New User? <a href="{% url 'microblog:register' %}">Click to Register!</a></p>
    </form>
{% endblock %}

mysite/microblog/templates/microblog/register.html
{% extends "microblog/base.html" %}

{% load bootstrap3 %}

{% block app_content %}
    <h1>Register</h1>
    <form role="form" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit='submit' %}{% endbuttons %}
    </form>
    </form>
{% endblock %}

mysite/microblog/templates/microblog/register_new.html
{% extends "microblog/base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <p>
            {{ field.label }}<br>
            {{ field }}<br>
            <span style="color: red;">{{ field.errors }}</span>
        </p>
        {% endfor %}
        <p><input type="submit" value="Submit"></p>
    </form>
{% endblock %}

mysite/microblog/templates/microblog/user.html
{% extends "microblog/base.html" %}

{% load bootstrap3 %}

{% block app_content %}
    <table class="table table-hover">
        <tr valign="top">
            <td><img src="{{ user.avatar_128}}"></td>
            <td><h1>User: {{ user.username }}</h1>
            {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
            {% if user.last_login %}<p>Last seen on: {{ user.last_login}}</p>{% endif %}
                <p>{{ user.user_set.count }} followers, {{ user.following.count }} following.</p>
            {% if user == current_user %}
            <p><a href="{% url 'microblog:edit_profile' %}">Edit your profile</a></p>
            {% elif not following %}
            <p>
                    <form action="{% url 'microblog:follow' username=user.username %}" method="post">
                        {% csrf_token %}
                        <p><input type="submit" value="Follow"></p>
                    </form>
                </p>
                {% else %}
            <p>
                    <form action="{% url 'microblog:unfollow' username=user.username %}" method="post">
                        {% csrf_token %}
                        <p><input type="submit" value="Unfollow"></p>
                    </form>
                </p>
                {% endif %}
            </td>
        </tr>
    </table>
    <hr>
    {% for post in page_obj %}
    <table>
        <tr valign="top">
            <td><img src="{{ post.user.avatar_36 }}"></td>
            <td><a href="{% url 'microblog:user' post.user.username %}">{{ post.user.username }}</a> says:<br>{{ post.body }}</td>
        </tr>
    </table>
    {% endfor %}
    <nav aria-label="...">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li>
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}